import * as Cfx from 'fivem-js';

export function setupMapEvents() { // if the event called without args it wont tp the player
  onNet("TXPVP:CORE:loadIsland", (coords: Cfx.Vector3) => {
    console.log("Received event")
    emit("TXPVP:CORE:unloadNorthYankton")
    Citizen.invokeNative('0x9A9D1BA639675CF1', "HeistIsland", true)
    Citizen.invokeNative('0x5E1460624D194A38', true)
    Citizen.invokeNative('0xF74B1FFA4A15FBEA', true)
    Citizen.invokeNative('0x53797676AD34A9AA', false)
    SetScenarioGroupEnabled('Heist_Island_Peds', true)
  })
  onNet("playerDied", () => {
    emit("TXPVP:CORE:unloadNorthYankton")
  })
  onNet("TXPVP:CORE:loadNorthYankton", (coords: Cfx.Vector3) => {
    console.log("Loading North Yankton")
    LoadMpDlcMaps()
    SetMinimapInPrologue(true)
  EnableMpDlcMaps(true)
  RequestIpl("FIBlobbyfake")
  RequestIpl("DT1_03_Gr_Closed")
  RequestIpl("v_tunnel_hole")
  RequestIpl("TrevorsMP")
  RequestIpl("TrevorsTrailer")
  RequestIpl("farm")
  RequestIpl("farmint")
  RequestIpl("farmint_cap")
  RequestIpl("farm_props")
  RequestIpl("CS1_02_cf_offmission")
  RequestIpl("prologue01")
  RequestIpl("prologue01c")
  RequestIpl("prologue01d")
  RequestIpl("prologue01e")
  RequestIpl("prologue01f")
  RequestIpl("prologue01g")
  RequestIpl("prologue01h")
  RequestIpl("prologue01i")
  RequestIpl("prologue01j")
  RequestIpl("prologue01k")
  RequestIpl("prologue01z")
  RequestIpl("prologue02")
  RequestIpl("prologue03")
  RequestIpl("prologue03b")
  RequestIpl("prologue04")
  RequestIpl("prologue04b")
  RequestIpl("prologue05")
  RequestIpl("prologue05b")
  RequestIpl("prologue06")
  RequestIpl("prologue06b")
  RequestIpl("prologue06_int")
  RequestIpl("prologuerd")
  RequestIpl("prologuerdb ")
  RequestIpl("prologue_DistantLights")
  RequestIpl("prologue_LODLights")
  RequestIpl("prologue_m2_door")  
  })
  onNet("TXPVP:CORE:unloadNorthYankton", () => {
    console.log("Unloading North Yankton")
    LoadMpDlcMaps()
    SetMinimapInPrologue(false)
    RemoveIpl("FIBlobbyfake")
    RemoveIpl("DT1_03_Gr_Closed")
    RemoveIpl("v_tunnel_hole")
    RemoveIpl("TrevorsMP")
    RemoveIpl("TrevorsTrailer")
    RemoveIpl("farm")
    RemoveIpl("farmint")
    RemoveIpl("farmint_cap")
    RemoveIpl("farm_props")
    RemoveIpl("CS1_02_cf_offmission")
    RemoveIpl("prologue01")
    RemoveIpl("prologue01c")
    RemoveIpl("prologue01d")
    RemoveIpl("prologue01e")
    RemoveIpl("prologue01f")
    RemoveIpl("prologue01g")
    RemoveIpl("prologue01h")
    RemoveIpl("prologue01i")
    RemoveIpl("prologue01j")
    RemoveIpl("prologue01k")
    RemoveIpl("prologue01z")
    RemoveIpl("prologue02")
    RemoveIpl("prologue03")
    RemoveIpl("prologue03b")
    RemoveIpl("prologue04")
    RemoveIpl("prologue04b")
    RemoveIpl("prologue05")
    RemoveIpl("prologue05b")
    RemoveIpl("prologue06b")
    RemoveIpl("prologue06_int")
    RemoveIpl("prologuerd")
    RemoveIpl("prologuerdb ")
    RemoveIpl("prologue_DistantLights")
    RemoveIpl("prologue_LODLights")
    RemoveIpl("prologue_m2_door") 
  })
} 
